### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by Javarome** [mtkennerly/kelonio#13]
Hey, thanks for this easy to integrate and TS perf framework.
I understand that it doesn't handle concurrent requests. Do you confirm and, if so, plan to support it?
Thanks.

**Comment by mtkennerly** [comment]
Hi! `measure` and `record` are both async and have built-in support for testing functions that return promises, so there shouldn't be any problems with this. Have you had any issues using it with concurrent code?

**Comment by Javarome** [comment]
Thanks for your answer. That the `iterations` parameter that made me think of being limited to a sequence only. 
So you mean launching a number of concurrent `benchmark.record()` and `Promise.all()` them could provide a quite realistic number of concurrent requests?

**Comment by mtkennerly** [comment]
Oh, gotcha. If you want to test all of the iterations concurrently, you can use the `serial` option:

```typescript
let measurement = await measure(
    () => { ... },
    { serial: false }
);
```

When `serial` is false, is uses `Promise.all` on the list of iterations:

https://github.com/mtkennerly/kelonio/blob/aaa79db6ef1f5863163e4e2e408a833163d884bb/src/index.ts#L216-L222
